### ISSUE TITLE
binding to win-hub headerinvoked event in an angular way

### ISSUE THREAD

**Issue by lorenjerickson** [winjs/angular-winjs#11]
I admit that this just may be ignorance on my part, but I am having trouble with detecting a click on a section header in a win-hub control.  I've scanned the source and found the ```onheaderinvoked``` event mentioned for this component, but I cannot bind to that event how I would expect to be able to with angular.  For example, I have tried variations on binding to the event in markup:

    <win-hub onheaderinvoked="headerInvoked">. . . </win-hub>

where ```headerInvoked``` is a method on the active ```$scope``` that receives an ```event``` object, but it does not get invoked.  Seems like I was able to get the ```$scope``` function to be invoked in one variation of this approach, but only without arguments, and because the ```event.detail.index``` is required to determine which section header was clicked, that was kind of useless.  The only way I have found to get the click detection to work is to put the following in my controller:

    document.getElementById('main-hub').addEventListener('headerinvoked', headerInvoked);

where ```headerInvoked``` in this case is not a function defined in the current ```$scope```, but just within the controller body.  This seems like a very un-angular way of doing this.  What an I missing?  Could you provide an example of this somewhere?

**Comment by TheWrathOfConst** [comment]
Event names are separated by dashes when in markup. Change `onheaderinvoked` to `on-header-invoked` like so:

`<win-hub on-header-invoked="headerInvoked($event)">. . . </win-hub>`

**Comment by lorenjerickson** [comment]
Thanks for the response.  I've tried it that way and it still doesn't work:

    <win-hub class="hub-page" id="main-hub" on-header-invoked="headerInvoked($event)">
        . . . 
    </win-hub>

and in the controller:

    $scope.headerInvoked= function(e) {
        . . . 
    }:

The scope function never gets invoked.  Sorry, I know this should be very basic.

**Comment by lorenjerickson** [comment]
ugh!  nevermind.  I had some crossed wires from trying this so many different ways.  uncrossed the wires and now it works.  sorry.
