### ISSUE TITLE
Depend on WinJS 4.0-preview package?

### ISSUE THREAD

**Issue by rigdern** [winjs/angular-winjs#13]
Should this depend on the WinJS 4.0-preview package rather than including WinJS.js directly?

**Comment by jayrenn** [comment]
Yes, that is the plan. @jseanxu will be updating the dependency in the near future.

**Comment by TheWrathOfConst** [comment]
Commit fa5d6ddabb has fixed this. Angular-winjs no longer uses an external directory with WinJS - it fetches WinJS 4.0.x from a CDN
