### ISSUE TITLE
No documentation on what WinJS API is exposed to Angular controllers

### ISSUE THREAD

**Issue by UzEE** [winjs/angular-winjs#16]
I've been experimenting for about a day now, but I still haven't quite figured out how to call WinJS methods from an Angular controller.

For instance, I'd like to toggle a SplitView when the user clicks a certain button, but I can't figure out how to get a reference to the SplitView being used in my controller.

Are WinJS controls exposed as services, or are their methods supposed to be bound to from HTML?

**Comment by TheWrathOfConst** [comment]
There's a win-control directive that allows you to expose the WinJS winControl object to your angular scope:

```html
<win-split-view win-control="variableOnScope">
```

That'll put the reference to your SplitView on the scope, so that you can then call methods on it.

**Comment by rigdern** [comment]
For the case of toggling the `SplitView`, you can bind to `SplitView`'s `pane-hidden` property.

**Comment by UzEE** [comment]
Thanks @rigdern, I figured out the binding part after I posted the issue. But I'd prefer having a reference to the control instances as well, which @TheWrathOfConst's solution provides.

It would help if the ```winControl``` directive is documented in the README (or some other place) though.

**Comment by AmazingJaze** [comment]
An example has been added to the readme
