### ISSUE TITLE
Content Dialog not available

### ISSUE THREAD

**Issue by risp** [winjs/angular-winjs#18]
I tried it like this (from the flyout example)

```html
<button id="contentDialogAnchor">Show a content dialog!</button>
<win-content-dialog anchor="'#contentDialogAnchor'">This is the content dialog content!!</win-content-dialog>
```

Maybe you could also add an example to the README.md also explaining how to use `title`, `primaryCommandText` and `secondaryCommandText`.

Thanks!

**Comment by rigdern** [comment]
@TheWrathOfConst let's add `ContentDialog` to the README.

**Comment by TheWrathOfConst** [comment]
I've improved the documentation in the readme. It now shows use of several properties and also demonstrates how to make a ContentDialog appear
