### ISSUE TITLE
General swipe behavior in 4.0

### ISSUE THREAD

**Issue by nikolafon** [winjs/angular-winjs#26]
While experimenting with controls in 4.0 version I notice that it supports very basic swipe behavior.  It is always short swipe in some direction. Then swipe is not sticky like in version 2 on Windows phone.  I was able to drag pivot item and when I release it will switch to the next or previous.  It is not the case in version 4. 0 on latest android chrome browser or ios, for example. What about edge swipe? Reveal side panel on an edge swipe?  And finally is there a way to swipe on a list item to reveal new options on the item itself,  like delete or archive on outlook app for ios? 
Thanks.

**Comment by AmazingJaze** [comment]
Hi @nikolafon, apologies for the long delay.

WinJS Pivot uses native browser CSS Scroll Snap Points http://dev.w3.org/csswg/css-snappoints/
to achieve the sticky swipe behavior you experienced in Windows Phone. Not every browser has implemented support for this yet but it is part of the W3C standard. In browsers where native features are not yet implemented we will fall back to the basic support you saw in the Android browser.

We don't currently have  pattern to reveal a pattern on edge swipe. WinJS is a cross browser library and I would expect that such a pattern would require support from a native event to inform WinJS when an edge swipe has occurred. Are you aware of other controls library supporting this pattern?
From a WinJS controls standpoint you could use a WinJS.UI.SplitView with ```js
closedDisplayMode: WinJS.UI.SplitView.ClosedDisplayMode.none,
```
To achieve the visual and layout requirements of that scenario, but you would still require an event to know when to toggle the SplitView.opened property to true.

Regarding your last question there is not currently support in the ListView to swipe on an item to reveal new options.The closest thing to this sort of listitem swipe behavior was "cross slide" which was removed from the ListView in WinJS 3.0  I have asked around and there are currently no plans to add support for this pattern in ListView

**Comment by nikolafon** [comment]
Thanks @AmazingJaze for the thorough explanation. In the end I went for my custom solutions and I can say I regret. Way to much cross browser issues. Going with WinJS you might not be able to achieve all the goals that you want it the app but at least what you have is going to work properly in all browsers.
