### ISSUE TITLE
ListView - type of GridLayout

### ISSUE THREAD

**Issue by FauClausen** [winjs/angular-winjs#27]
How do you change the layout to be the type of a GridLayout (or others)

/Thanks

**Comment by TheWrathOfConst** [comment]
Use the win-grid-layout directive inside of your win-list-view:

```js
<win-list-view>
    <win-grid-layout></win-grid-layout>
</win-list-view>
```

**Comment by sondreb** [comment]
Sorry for commenting on old issue, but this is another example that there is a serious need for better documentation of Angular WinJS. There is a property named layout on the list-view, I have tried to set it to a lot of different things with nothing working. Having to search closed issues on Github is not the proper way for learning a library like this.
