### ISSUE TITLE
Angular is undefined

### ISSUE THREAD

**Issue by jolleman** [winjs/angular-winjs#38]
Hi im trying to make a universal app with angular-winjs but i get a angular is undefined and i dont know what to do. i downloaded the starter template from the trywinjs website.

Here is my code:

```
<!DOCTYPE html>
<html ng-app="AngularWinJSApp" ng-controller="AngularWinJSAppController" ng-csp>
<head>
    <title>WinJS project</title>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js"></script>

    <link rel="stylesheet" href="lib/Microsoft.WinJS.4.0/css/ui-light.css" />
    <script src="lib/Microsoft.WinJS.4.0/js/WinJS.min.js"></script>
    <script src="lib/angular-winjs/angular-winjs.js"></script>

    <link rel="stylesheet" href="css/default.css" />
    <script src="js/default.js"></script>
</head>
<body class="phone">
    <a href="https://github.com/winjs/angular-winjs" target="_blank">Learn more about Angular-WinJS</a>
</body>
</html>
```
Any help would be appreciated:)

Regards Joel

**Comment by AmazingJaze** [comment]
Hi @jolleman, the problem may be that the version of WinJS UI are using doesn't align to the version of angular-winjs. Currently the angular-winjs project is aligned to WinJS 4.0 Preview, which you can also get from [trywinjs](http://try.buildwinjs.com/#get). The version of WinJS 4.0 that your build of visual studio is using may be a newer version of WinJS 4.0.

The first thing I would try is downloading WinJs 4.0 Preview from the [trysite]{http://try.buildwinjs.com/#get}, adding it locally to you project, and replace the references to 
```html
<link rel="stylesheet" href="lib/Microsoft.WinJS.4.0/css/ui-light.css" />
<script src="lib/Microsoft.WinJS.4.0/js/WinJS.min.js"></script>
```
with the src to your local copy of WinJS 4.0 preview, and see if that doesn't resolve your issue.

We plan to update angular-winjs and all the samples on the try site to use WinJS 4.0, shortly after the upcoming release of WinJS 4.0 itself.

----
If the above doesn't resolve your issue, can you provide a page/app which repros this behavior? You can share it using OneDrive as described [on our wiki](https://github.com/winjs/winjs/wiki/How-to-share-repros-of-issues-with-WinJS).

**Comment by jolleman** [comment]
Hi!

ive tried that. I get an angular undefined at line 363 in angular-winjs. Does angular-winjs require the angularjs library?

var module = angular.module("winjs", []);

Regards Joel

**Comment by AmazingJaze** [comment]
The angularjs library does need to be loaded, but it looks like you are already doing that correctly in the code snippet you pasted above. 

Can you provide a page/app which repros this behavior as described [on our wiki](https://github.com/winjs/winjs/wiki/How-to-share-repros-of-issues-with-WinJS). So we can take a look at it?

**Comment by AmazingJaze** [comment]
@jolleman, Thinking about this some more, it might be a conflict with Universal App script loading policies.  I assume you are seeing this issue when you try to run as a Win 10 app in visual studio?

If you are not able to get us a repro page/app to investigate, I would try running the same HTML file on a website, or copy the Angular library locally to your Visual Studio project and reference it from there.
