### ISSUE TITLE
Some control changes aren't propagated back to the scope

### ISSUE THREAD

**Issue by rigdern** [winjs/angular-winjs#45]
When the user interacts with a control causing a control's property to change (e.g. the user closing a SplitView causes the `paneOpened` property to be false), this property change should be propagated into the angular scope.

We do this for most properties but we missed some:
  - Pivot: `selectionchanged` event affects `selectedIndex` and `selectedItem`
  - SemanticZoom: `zoomchanged` event affects `zoomedOut`

**Comment by AmazingJaze** [comment]
@rigdern  is this the same as #4 ?

**Comment by rigdern** [comment]
It looks like they're related. #4 seems more comprehensive. #4 asks to do scrollPosition which requires batching because it's noisy and we don't do anything like that now.

This bug should be much easier because it only uses techniques we've already used in other places.

Ask @TheWrathOfConst what properties he had in mind for #4. I thought we already handled most of them.
