### ISSUE TITLE
ensureVisible ?

### ISSUE THREAD

**Issue by sensiblearts** [winjs/angular-winjs#53]
I'm new at both angular and winjs, so sorry if this is out of place. 

I would love to have an first-item-visible property or some such for this listview.

If I try to force scroll to a listview item using ensureVisible (or setting indexOfFirstVisible), the property is not set (-1), because datasource is empty (too early).

But when I try tapping into onloadingstatechanged, it never seems to fire. (Not sure I'm doing this right.)

So I tried waiting 2 seconds, all data is clearly loaded, and I get this error:
<pre><code>
   var list_v = document.getElementsByClassName("win-listview");
   if (list_v.length) {
               list_v = list_v[0].winControl;
               if (list_v) {
                           $timeout(function() {
                                list_v.ensureVisible(item_index);   // throws error below
                            }, 2000);  // ensure all data is loaded
               }
   }
</code></pre>
TypeError: Cannot read property 'firstIndexDisplayed' of null
    at ListView_ctor._Base.Namespace.define.ListView._Base.Namespace._lazy._Base.Class.define.indexOfFirstVisible.get [as indexOfFirstVisible] (WinJS.js:46194)

**Comment by jayrenn** [comment]
@sensiblearts Have you tried using the [ListView.indexOfFirstVisible](https://msdn.microsoft.com/en-us/library/windows/apps/hh700691.aspx) property?

**Comment by jayrenn** [comment]
@sensiblearts Can you provide a repro of your code? You should be able to use the [indexOfFirstVisible](https://msdn.microsoft.com/en-us/library/windows/apps/hh700691.aspx) property to get the first visible item (or set, if you wish to jump to a particular item).

**Comment by sensiblearts** [comment]
Basically, I'm loading listview data in $scope.init and trying to time when to scroll to the right object.

<pre><code>
   $scope.backToTab = function() {
           // code omitted here, switches to the tab with the listview
           if (item_index) {  // e.g., 7 to scroll to 7th item
                   var list_v = document.getElementsByClassName("win-listview");
                   if (list_v.length) {
                       list_v = list_v[0].winControl;
                       if (list_v) {
                           //not working:
                           list_v.indexOfFirstVisible = item_index;
                           console.log(list_v.indexOfFirstVisible); //  -1, regardless of what I set it to
  
                           // of if I add another timeout delay here, I get error as in my previous post
 
                        }
                    }
               }
           }
        };
        $scope.init = function () {
             $http.get('api/mygroups',{broadcastError:true}).
                  success(function(data, status, headers, config) {
                    $scope.groups = data.groups || [];   // data for listview
                    //...
                    $timeout( $scope.backToTab, 100);  // see above
                  }).
                  error(function(data, status, headers, config) {
                  });
         };
  </code></pre>

**Comment by AmazingJaze** [comment]
Hi @sensiblearts , thanks for the additional information. Just to clarify, are you only seeing this problem when trying to navigate back to a ListView that was already rendered? Or do you see this problem the first time a ListView is constructed and are unable to get ensureVisible() to work correctly? 

When the problem occurs, does the ListView element have proper dimensions when you are setting the data or trying to call ensureVisible() ? If the ListView element can not accurately measure itself and its items,  for example. due to a parent element having display:none; , then you might find that calling ListView.forceLayout() or the _less_ expensive ListView.recalculateItemPosition may rectify this problem for you.

Finally, I see that you are using ``` document.getElementsByClassName("win-listview")[0] ```  to get a hold of the listview element, is it possible that the element at index 0 is not actually the correct listview element? Out of curiosity what is the length of the array that getElementsByClassName is returning when that code is executed?

If none of the above addresses your issue, can you share a page or app that repros the bug? If you want to send us files, you can use OneDrive as described in our [described in our wiki](https://github.com/winjs/winjs/wiki/How-to-share-repros-of-issues-with-WinJS).

**Comment by AmazingJaze** [comment]
Edited my previous response for extra clarification.

**Comment by sensiblearts** [comment]
Thank you so much for the detailed reply.

I built a test app by stripping out unrelated code, and (probably no
surprise to you), indexOfFirstVisible works as it is supposed to!

I will figure out what in my full app is causing the side effect, and I
will pass along the information just in case it is relevant to your efforts.

D. Alm




On Wed, Jul 29, 2015 at 7:56 PM, AmazingJaze <notifications@github.com>
wrote:

> Hi @sensiblearts <https://github.com/sensiblearts> , thanks for the
> additional information. Just to clarify, are you only seeing this problem
> when trying to navigate back to a ListView that was already rendered? Or do
> you see this problem the first time a ListView is constructed and are
> unable to get ensureVisible() to work correctly?
>
> When the problem occurs, does the ListView element have proper dimensions
> when you are setting the data or trying to call ensureVisible() ? If the
> ListView element can not accurately measure itself and its items, for
> example. due to a parent element having display:none; , then you might find
> that calling ListView.forceLayout() or the *less* expensive
> ListView.recalculateItemPosition may rectify this problem for you.
>
> Finally, I see that you are using
> document.getElementsByClassName("win-listview")[0] to get a hold of the
> listview element, is it possible that the element at index 0 is not
> actually the correct listview element? Out of curiosity what is the length
> of the array that getElementsByClassName is returning when that code is
> executed?
>
> If none of the above addresses your issue, can you share a page or app
> that repros the bug? If you want to send us files, you can use OneDrive as
> described in our described in our wiki
> <https://github.com/winjs/winjs/wiki/How-to-share-repros-of-issues-with-WinJS>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/winjs/angular-winjs/issues/53#issuecomment-126131963>.
>



-- 
</>
David Alm
