### ISSUE TITLE
Error while creating AppBarCommand in WinJS 2.1

### ISSUE THREAD

**Issue by gabmontes** [winjs/angular-winjs#56]
We are writing an AngularJS app for Windows Phone 8.1, which uses WinJS 2.1, and an error is thrown while creating the app bar commands at https://github.com/winjs/angular-winjs/blob/master/js/angular-winjs.js#L338 because `controlConstructor` is `undefined`. The error traces back to https://github.com/winjs/angular-winjs/blob/master/js/angular-winjs.js#L509 as `WinJS.UI.Command` is `undefined` in this version of WinJS. When changing `WinJS.UI.Command` to `WinJS.UI.AppBarCommand`, the app bar and its commands are correctly created and no issues are thrown.

Since `WinJS.UI.Command` is not defined in WinJS 2.1, `WinJS.UI.Command === WinJS.UI.AppBarCommand` in WinJS 4.0 and no tests are affected, is it safe to change the object name in L509 to support WinJS 2.1?

**Comment by jdalton** [comment]
> WinJS 4.0 and no tests are affected, is it safe to change the object name in L509 to support WinJS 2.1?

I don't see the harm. @AmazingJaze can confirm.

**Comment by AmazingJaze** [comment]
I think it should be fine.
