### ISSUE TITLE
How to pass parameters to function?

### ISSUE THREAD

**Issue by nanivijay** [winjs/angular-winjs#57]
Hi

How can I pass parameters to function onfootervisibilitychanged()?

 <win-list-view item-data-source=".Items"  
                       on-footer-visibility-changed="onfootervisibilitychanged()">

**Comment by AmazingJaze** [comment]
Hi @navijay,

You if you are trying to get the event object passed into your event handler you should be able to do the following:

```js
function onfootervisibilitychanged(ev){
  // make sure your function expects a parameter
}
```
```HTML
<!-- When the browser calls your function, It will have already defined a variable named "event" in the same context. This variable represents the event object that you want passed to your function -->
<win-list-view on-footer-visibility-changed="onfootervisibilitychanged(event)">
```

Let me know how that work out for you.

**Comment by nanivijay** [comment]
Sure thanks for the update. I will check

**Comment by nanivijay** [comment]
hi
even though I pass event as a parameter I am getting undefined in the
function. it will be great help if you can provide some sort of sample.

Appreciate u r help.

Thx

On Thu, Aug 13, 2015 at 11:07 AM, vijay kumar <nani.vijay@gmail.com> wrote:

> Sure thanks for the update. I will check
> On Aug 13, 2015 11:05 AM, "AmazingJaze" <notifications@github.com> wrote:
>
>> Hi @navijay <https://github.com/navijay>,
>>
>> You if you are trying to get the event object passed into your event
>> handler you should be able to do the following:
>>
>> function onfootervisibilitychanged(ev){
>>   // make sure your function expects a parameter
>> }
>>
>> 
>> <win-list-view on-footer-visibility-changed="onfootervisibilitychanged(event)">
>>
>> Let me know how that work out for you.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/winjs/angular-winjs/issues/57#issuecomment-130782848>
>> .
>>
>


-- 
VIJAY KUMAR

**Comment by AmazingJaze** [comment]
hi @nanivijay , Apologies my earlier suggestion only works for raw JavaScript scenarios. Angular is a little different, but only a little. To get this working in angular-winjs you need to pass the $event object as the function parameter when specifying the event listener.  

`on-footer-visibility-changed="handler($event)"`

Here is a working sample HTML file that does just that. If you run it with debug tools open you can see that when the debugger statement breaks, the event object is present. 

```HTML
<!DOCTYPE html>
<html ng-app="testApp" ng-controller="test">
<head>
    <title>ListView Test</title>
    <script src="js/angular.js"></script>
    <script src="js/base.js"></script>
    <script src="js/ui.js"></script>
    <script src="js/angular-winjs.js"></script>
    <link href="css/ui-dark.css" rel="stylesheet" />
</head>
<body>

    <script>
        angular.module('testApp', ['winjs']).controller("test", function ($scope) {
          
            $scope.ratings = new WinJS.Binding.List([{ value: 1 }, { value: 2 }, { value: 1 }, { value: 2 }, { value: 1 }, { value: 2 }]);
            $scope.selection = "multiselect";

            $scope.head = document.getElementById("head");
            $scope.foot = document.getElementById("foot");

            $scope.handler = function (ev) {
                debugger;
            };

        });
    </script>

    <div id="head" style="background-color:red; height: 30px; width:30px;"></div>
    <div id="foot" style="background-color:blue; height: 30px; width:30px;"></div>

    <!--on-loading-state-changed="handler()"--> 

    <win-list-view header="head" footer="foot" 
                   on-footer-visibility-changed="handler($event)" 
                   item-data-source="ratings" 
                   selection="selection">
        <win-item-template>
            This list view item's rating is: {{item.data.value}}</br> 
            This list view item's rating is: {{item.data.value}}</br>
            This list view item's rating is: {{item.data.value}}</br>
            This list view item's rating is: {{item.data.value}}</br>
            This list view item's rating is: {{item.data.value}}</br>
            This list view item's rating is: {{item.data.value}}</br>
            This list view item's rating is: {{item.data.value}}</br>
            This list view item's rating is: {{item.data.value}}</br>
            This list view item's rating is: {{item.data.value}}</br>
            This list view item's rating is: {{item.data.value}}</br>
            This list view item's rating is: {{item.data.value}}</br>
            This list view item's rating is: {{item.data.value}}</br>
            This list view item's rating is: {{item.data.value}}</br>
            This list view item's rating is: {{item.data.value}}</br>
            This list view item's rating is: {{item.data.value}}</br>
            This list view item's rating is: {{item.data.value}}</br>
        </win-item-template>
        <win-list-layout></win-list-layout>
    </win-list-view>
</body>
</html>
```

**Comment by nanivijay** [comment]
This is great. Thanks for the code snippet and prompt response.
