### ISSUE TITLE
Cannot use ng-repeat inside win-app-bar

### ISSUE THREAD

**Issue by gabmontes** [winjs/angular-winjs#59]
Tried to dynamically generate the commands in a `win-app-bar` using `ng-repeat` as follows:

```html
<win-app-bar id="appbar">
  <win-app-bar-command ng-repeat="label in ['text1', 'text2']" label="label" icon="'add'">
  </win-app-bar-command>
</win-app-bar>
```

When running the app, the following error is thrown:

```
TypeError: Unable to get property 'insertBefore' of undefined or null reference 
  at after (angular.js:3201:7)
```

which maps to a `parent.insertBefore` call during the transcluding process. This is running in a Windows Phone 8.1 with latest angular-winjs@3.1.1 and angular.js@1.3.17. Can you please advice on why this is failing?

**Comment by gabmontes** [comment]
@jdalton can you please comment on this issue? I expected someone on the team to do that before closing it. Thanks!

**Comment by jdalton** [comment]
Hi @gabmontes! My apologies. Unfortunately there's lots of stale issues across the WinJS projects and commenting on all of them is impractical. I thinking is that it's better to close an issue as `stale` than leave it open with the false hope of tackling.

**Comment by gabmontes** [comment]
@jdalton fair enough. Thanks!
