### ISSUE TITLE
Content Dialog - Multiple controls on page are not supported

### ISSUE THREAD

**Issue by P4trik** [winjs/angular-winjs#60]
I render multiple Content Dialog controls on my HTML site. 
If I click the associated button from one of them, all message dialogs are appearing.

Is it a bug or just not possible to have multiple content dialog controls on one page?

**Comment by AmazingJaze** [comment]
Hi @P4trik  it is possible to have multiple Content Dialog controls on your HTML site. 

Do you see this issue specific only when you use the angular-winjs adapter, or are you able to reproduce it with just WinJS as well?
