### ISSUE TITLE
Disable win-flip-view animation 

### ISSUE THREAD

**Issue by gabmontes** [winjs/angular-winjs#63]
I have a `win-flip-view` control and need to replace the last item. When I do that while having the last item on screen, it fades out, the flipview goes back to the previous item and the new item. The new item is correctly created but I have to scroll to it again.

Is there any option to disable the animation and do the replacement in site so the user having the replaced item on the screen just sees the new content, no scroll? If not, how can that be done?

**Comment by jayrenn** [comment]
Hi @gabmontes, there is no such option available today. I've added this to our list of feature requests, and will continue to track this internally. Thanks!
