### ISSUE TITLE
When clicking on rating stars, our UI is not updating on first click.

### ISSUE THREAD

**Issue by tyroneallen281** [winjs/angular-winjs#68]
Code:  
<win-rating max-rating="maxRating" user-rating="userrating" on-change="bookRate()" ></win-rating>

We are experiencing an issue that when a user clicks on the rating stars for the first time after page load the rating object does not show this rating, it seems to be caused but the following in your code.

```js
_onUserRatingChanged: function () {
                    if (!this._disabled) {
                        this._closeTooltip();
                        // Only submit a change event if the user has altered the rating control value via PREVIEWCHANGE event.
                        if (this._userRating !== this._tentativeRating && !this._lastEventWasCancel && !this._lastEventWasChange) {
                            this.userRating = this._tentativeRating;
                            this._raiseEvent(CHANGE, this._userRating);
                        } else {
                            this._updateControl();
                        }
                    }
                }
```

The  `if (this._userRating !== this._tentativeRating` part of the If is false causing the system to not update.

I am not sure why this is please look into it as help asap.

Regards Tyrone

**Comment by jdalton** [comment]
Unfortunately it doesn't look like I'll have the time to investigate. However, please feel free to update the issue any further findings.
