### ISSUE TITLE
win-split-view-pane-toggle height and win-split-view height together not 100%/vh

### ISSUE THREAD

**Issue by xdvarpunen** [winjs/angular-winjs#70]
Hi,

I found that win-split-view-pane-toggle height and win-split-view height are together not 100%/vh. To overcome this problem, set following style into win-split-view; height:calc(100% - 48px). Button is set as 48px height.

IE/Edge works fine with this solution but in Chrome/Firefox the toggle part is 60px... so for that calc should be changed to -60px...

To repeat the problem of win-split-view-pane-toggle height and win-split-view height together not 100%/vh, create win-split-view as in README.md and set splitview content as 100vh. Then paint text for instance and drag down and you will see that content actually scrolls down and hides the toggle button. win-split-view with win-split-view-pane-toggle is in demo 100vh + 48px.

In the nutshell; ```<win-split-view id="splitView" style='height:calc(100% - 48px)'>``` fixes height problem.

Thank you for your support,
XDVarpunen

**Comment by xdvarpunen** [comment]
IE/Edge works fine with this solution but in Chrome/Firefox the toggle part is 60px... so for that calc should be changed to -60px...

**Comment by jdalton** [comment]
Hi @xdvarpunen! Would you be open to creating a PR to resolve the issue?

**Comment by xdvarpunen** [comment]
Hi @jdalton! Sure (: This requires separate .css file in this case.

**Comment by xdvarpunen** [comment]
Hi @jdalton, the issue now is that .win-spliltpanetoggle is not same size in different browsers. This is WinJS CSS problem, not angular-winjs problem. Sorry for my misunderstanding :stuck_out_tongue_winking_eye:
