### ISSUE TITLE
Support for Angular 2.0

### ISSUE THREAD

**Issue by sasivarnan** [winjs/angular-winjs#86]
When can we expect WinJS with Angular 2.0? 
It is early to ask this question. But it is worth to do. 
For Microsoft, it won't be a tough thing, as Angular 2 can be written in TypeScript. 

Hope we will see angular2-winjs soon.

**Comment by humale** [comment]
@sasivarnan, refer to this thread regarding your feature request: https://github.com/winjs/winjs/issues/1622#issuecomment-213136589
