### ISSUE TITLE
Support for Angular 1.4/1.5

### ISSUE THREAD

**Issue by albatrosary** [winjs/angular-winjs#88]
Hi.

Now Angular version is 1.3, do you have any plans to 1.4 / 1.5?
It is an error if run in 1.5.
I want you to the version up.

Thank you.

**Comment by jdalton** [comment]
Related to #86.

**Comment by sondreb** [comment]
One bug with 1.5 is that the split view adds ="true" on the win-pivot. Angular 1.5 supports named transcludes, so it looks for an element named "true". ng-transclude should not set to true, only add the attribute without content.

```
Error: [$compile:noslot] No parent directive that requires a transclusion with slot name "true". Element: <div ng-transclude="true"
```

**Comment by AndreasM009** [comment]
Hi,
I currently updated my application to AngularJS 1.5.3.
It seems that the WinJS ListView does not work with AngularJS 1.5.3.
I get the following error when Angular tries to compile win-list-view directive:
Error: [$compile:noslot] http://errors.angularjs.org/1.5.3/$compile/noslot? ....
Any ideas?

Thank you

**Comment by DimiGrigoriadis** [comment]
With introduction of AngularJS 1.5.x transclusion was changed to support the long awaited multi-transcludes. Since ListView adds transclude=true, Angular is looking for the transclude slot named "true". See @sondreb explanation. So you should use a version < 1.5.x. I'm using 1.4.8 and everything works fine.

**Comment by sensiblearts** [comment]
I just froze a copy of angular-winjs.js and did a search and replace:
// replaced: ng-transclude='true'
// with: ng-transclude

Seems to work fine.

**Comment by humale** [comment]
@albatrosary thanks for the question! It's been answered here: https://github.com/winjs/winjs/issues/1622#issuecomment-213136589

**Comment by albatrosary** [comment]
@humale thank you! Take a look at.
