### ISSUE TITLE
winAppBarCommand doesn't have support for type='content'

### ISSUE THREAD

**Issue by mtycholaz** [winjs/angular-winjs#9]
The problem is that the template is set to a BUTTON element by default. WinJS throws an error if the element is not of type DIV. 

Basically to fix this, I believe you need to add a compile function to the directive and replace the element based on it's type. 

    if(type == 'content')
        template = "<div ng-transclude='true'></div>";
    else
        template = "<button ng-transclude='true'></button>"

    element.replaceWith(template);

**Comment by TheWrathOfConst** [comment]
Sure can!
